### ISSUE TITLE
support for full native functionality without python involved.

### ISSUE THREAD

**Issue by nikhil-swamix** [chroma-core/chromadb-default-embed#1]
### Question

is it possible to run chroma server competely in client side frontend? memory? i mean that default embedding function and ranking will be available? i have read the readme , seems its copy paste off transformers.js , and unable to figure out.

**Comment by beggers** [comment]
Hey @nikhil-swamix! Chroma is written in Python so you can't run it completely in a javascript process. Your only options are to run it in a python process or docker container and connect to it over the network.

**Comment by nikhil-swamix** [comment]
@beggers , https://docs.oramasearch.com/open-source/ , in future is something like this possible? i have used chroma in production, but want to offload Vsearch to client side. these are my motivations, please share your thought process. thanks
- Regards

**Comment by jeffchuber** [comment]
@nikhil-swamix we are interested in making it easy to run "edge" vector search in the future!
